# Generated by Django 4.2.6 on 2023-10-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto_emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('tipo_perfil', models.CharField(max_length=20)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionLaboral',
            fields=[
                ('id_informacion_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmpleado',
            fields=[
                ('id_contacto_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('id_contacto_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.contactoemergencia')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.area')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id_carga_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.departamento'),
        ),
        migrations.AddField(
            model_name='area',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.empleado'),
        ),
    ]
