# Generated by Django 4.2.6 on 2023-11-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_departamento_id_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='nombre',
            new_name='nombre_area',
        ),
        migrations.RenameField(
            model_name='cargafamiliar',
            old_name='nombre',
            new_name='nombre_carga',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='nombre',
            new_name='nombre_cargo',
        ),
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='nombre',
            new_name='nombre_contacto',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre',
            new_name='nombre_departamento',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombre_empleado',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='nombre',
            new_name='nombre_perfil',
        ),
    ]
