# Generated by Django 4.2.6 on 2023-11-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_nombre_area_nombre_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargafamiliar',
            old_name='genero',
            new_name='genero_carga',
        ),
        migrations.RenameField(
            model_name='cargafamiliar',
            old_name='parentesco',
            new_name='parentesco_carga',
        ),
        migrations.RenameField(
            model_name='cargafamiliar',
            old_name='rut',
            new_name='rut_carga',
        ),
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='relacion',
            new_name='relacion_contacto',
        ),
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='telefono',
            new_name='telefono_contacto',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='direccion',
            new_name='direccion_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='genero',
            new_name='genero_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='rut',
            new_name='rut_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='telefono',
            new_name='telefono_empleado',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='clave',
            new_name='clave_perfil',
        ),
    ]
