# Generated by Django 4.2.6 on 2023-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_rename_genero_cargafamiliar_genero_carga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rut_perfil',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('Recursos Humanos', 'Recursos Humanos')], max_length=20),
        ),
    ]
