# Generated by Django 4.2.6 on 2023-11-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_empleado_genero_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rut_perfil',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('recursos humanos', 'Recursos Humanos')], max_length=20),
        ),
    ]
